using System.Collections.Generic;
using ProjectEulerCSharp.EulerMath;

namespace ProjectEulerCSharp.EulerProblems._0040s
{
    [Euler(
        title: "Problem 44: Pentagon Numbers",
        description: @"Pentagonal numbers are generated by the formula, Pn = n(3n - 1)/2. The first ten pentagonal numbers are:

            1, 5, 12, 22, 35, 51, 70, 92, 117, 145

It can be seen that P4 + p7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 - 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?")
    ]
    // ReSharper disable once UnusedType.Global
    public class Problem0044 : ISolution<int>
    {
        public bool HaveImplementedAnalyticSolution => true;

        public int BruteForceSolution()
        {
            // I ran this a few times with a much bigger upper bound, I narrowed it down to 2500 to try and find a small value that worked
            var upperBound = 2_500;
            var pentagonals = new int[upperBound];
            for (var i = 0; i < upperBound; i++)
            {
                pentagonals[i] = (int)FigurateNumbers.Pentagonal(i+1);
            }
            // using this HashSet<int> to see if a number is in the pentagonals calculated is *much* faster
            var pantagonalLookup = new HashSet<int>(pentagonals);

            for (var j = 0; j < upperBound; j++)
            {
                var jPent = pentagonals[j];
                for (var k = 0; k < j; k++)
                {
                    var kPent = pentagonals[k];
                    var delta = jPent - kPent;
                    if (pantagonalLookup.Contains(delta))
                    {
                        if (pantagonalLookup.Contains(jPent + kPent))
                        {
                            return delta;
                        }
                    }
                }
            }

            return -1;
        }

        public int AnalyticSolution()
        {
            // Somewhat surprisingly the brute force solutions beats the snot out of this one.
            var j = 1;
            while (true)
            {
                var jPent = FigurateNumbers.Pentagonal(j);
                var k = 1;
                while (k < j)
                {
                    var kPent = FigurateNumbers.Pentagonal(k);
                    if (FigurateNumbers.IsPentagonal(jPent + kPent))
                    {
                        var diff = jPent - kPent;
                        if (FigurateNumbers.IsPentagonal(diff))
                        {
                            return (int)diff;
                        }
                    }
                    k++;
                }
                j++;
            }
        }

        public int ExpectedSolution()
        {
            return 5_482_660;
        }
    }
}
